# Generated by Django 2.2.1 on 2019-11-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='details',
            new_name='medication_details',
        ),
    ]
