# Generated by Django 2.2.1 on 2019-12-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20191130_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='Rostered_physician',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
